version: "3"

services:
  auth:
    build:
      ./auth
    ports:
      - "6000:6000"
  user:
    build:
      ./user
    ports:
      - "5000:5000"
  game:
    build:
      ./game
    ports:
      - "5001:5001"
    depends_on:
      - auth
      - user
